export type EyewearProduct = {
  id: string;
  brand: string;
  nameAr: string;
  model: string;
  category: "Sunglasses" | "Prescription" | "Sports" | "Luxury" | "Kids";
  frameMaterial: string;
  lensType: string;
  rating: number;
  reviewCount: number;
  priceInPi: number;
  imageColor: string;
  accentColor: string;
  badge?: string;
};

export const EYEWEAR_PRODUCTS: EyewearProduct[] = [
  {
    id: "1",
    brand: "Ray-Ban",
    nameAr: "راي-بان ويفرير",
    model: "Wayfarer Classic",
    category: "Sunglasses",
    frameMaterial: "Acetate",
    lensType: "UV400 Polarized",
    rating: 4.8,
    reviewCount: 2341,
    priceInPi: 45,
    imageColor: "#1a1a2e",
    accentColor: "#7C3AED",
    badge: "Best Seller",
  },
  {
    id: "2",
    brand: "Gucci",
    nameAr: "غوتشي فاشن",
    model: "GG0061S Gold",
    category: "Luxury",
    frameMaterial: "Metal",
    lensType: "Anti-Reflective",
    rating: 4.9,
    reviewCount: 876,
    priceInPi: 320,
    imageColor: "#2d1b00",
    accentColor: "#F59E0B",
    badge: "Luxury",
  },
  {
    id: "3",
    brand: "Oakley",
    nameAr: "أوكلي هولبروك",
    model: "Holbrook Sport",
    category: "Sports",
    frameMaterial: "O-Matter",
    lensType: "Prizm Polarized",
    rating: 4.7,
    reviewCount: 1543,
    priceInPi: 78,
    imageColor: "#0a1628",
    accentColor: "#ef4444",
    badge: "20% OFF",
  },
  {
    id: "4",
    brand: "Prada",
    nameAr: "برادا فريم",
    model: "SPR 68Z Cat-Eye",
    category: "Luxury",
    frameMaterial: "Acetate",
    lensType: "Gradient Tint",
    rating: 4.8,
    reviewCount: 412,
    priceInPi: 280,
    imageColor: "#1a0a2e",
    accentColor: "#a855f7",
    badge: "New",
  },
  {
    id: "5",
    brand: "Maui Jim",
    nameAr: "ماوي جيم بولارد",
    model: "Peahi Polarized",
    category: "Sunglasses",
    frameMaterial: "Nylon",
    lensType: "PolarizedPlus2",
    rating: 4.6,
    reviewCount: 987,
    priceInPi: 89,
    imageColor: "#0a1e2a",
    accentColor: "#0ea5e9",
  },
  {
    id: "6",
    brand: "Tom Ford",
    nameAr: "توم فورد اتش",
    model: "FT0237 Snowdon",
    category: "Luxury",
    frameMaterial: "Metal + Acetate",
    lensType: "Brown Gradient",
    rating: 4.9,
    reviewCount: 321,
    priceInPi: 199,
    imageColor: "#1c1208",
    accentColor: "#d97706",
  },
  {
    id: "7",
    brand: "Nike",
    nameAr: "نايك رياضي",
    model: "Vision Elite",
    category: "Sports",
    frameMaterial: "Grilamid TR-90",
    lensType: "Vented Lens",
    rating: 4.5,
    reviewCount: 2100,
    priceInPi: 55,
    imageColor: "#0f1923",
    accentColor: "#22c55e",
    badge: "15% OFF",
  },
  {
    id: "8",
    brand: "Persol",
    nameAr: "برسول فولدينغ",
    model: "714 Folding",
    category: "Sunglasses",
    frameMaterial: "Acetate",
    lensType: "Crystal Glass",
    rating: 4.7,
    reviewCount: 654,
    priceInPi: 155,
    imageColor: "#1a0f00",
    accentColor: "#b45309",
  },
  {
    id: "9",
    brand: "Lacoste",
    nameAr: "لاكوست أطفال",
    model: "Kids L3651S",
    category: "Kids",
    frameMaterial: "Flexible TR-90",
    lensType: "UV400 Protection",
    rating: 4.6,
    reviewCount: 389,
    priceInPi: 28,
    imageColor: "#001a0a",
    accentColor: "#16a34a",
    badge: "Kids Pick",
  },
  {
    id: "10",
    brand: "Silhouette",
    nameAr: "سيلويت بصري",
    model: "Titan Minimal",
    category: "Prescription",
    frameMaterial: "Titanium",
    lensType: "Progressive",
    rating: 4.8,
    reviewCount: 234,
    priceInPi: 240,
    imageColor: "#0d0d1a",
    accentColor: "#6366f1",
  },
];
